### ISSUE TITLE
roadmap to a v0.2 revision

### ISSUE THREAD

**Issue by tyalie** [tyalie/TyK380-keyboard#1]
Issues and improvements that I've discovered with the v0.1. 

Just to note here at the start: I'm already using the keyboard on a daily basis. The major features like being a keyboard, charging, USB connection and on/off (with a hotfix) already work perfectly. This is to get to a revision that doesn't require botch wires, has cool blinky stuff and is easier to solder and source.

### Problems
- [x] battery MOSFET is __still__ wired incorrectly
    - [x] on/off switch has a third pin -> no inversion needed
    - [x] verify, that mosfet pin layout matches employed DMN2056U nMOS (DGS)
- [x] change footprint for WS2812 LEDs (actually use the correct one)
- [ ] try out a thinner PCB (Aislers 1.6mm is too thick)

### Improvements
- [x] #2
- [x] change global lables to net labels for KiCad convention compliance
- [ ] (optional) add trace interface :D
  - the nRF52840 has a Cortex-M trace interface. I really want to use that
- [ ] Add cool logo

### Last steps
- [ ] verify spacing
- [ ] verify that all components have right layout

#### Issues
- [x] USB require resistors between D+ and D-

**Comment by tyalie** [comment]
Comments I received from zmk discord ^^

- [x] maybe use E73-2G4M08S1C
- [ ] for voltage divider 750kOhm to VBAT and 2MOhm to GND
  - [x] gnd can actually be tied to additional GPIO pin -> allows removing current flow during no measurement
- [x] ability to cut off power to LEDs (see cpressers work)
- [x] wire LEDs to vbat instead of 3.3V
- [ ] ~~maybe use 3V instead of 3.3V -> more range with LDO~~
  - reason for removal: the employed voltage regulator (XC6220) scales its output voltage linearly with the input voltage until e.g. 3.3V. The lowest possible input voltage (dropout voltage) ofc. depends on the load, but at 1A the LDO will dropout only at 650mV. The li-ion is fully dead until that point.
  - The only pro argument left would be a minimally increase of efficiency, but 3.3V worked previously and I'm too superstitious to change it  
- [x] maybe SRV05 or USBLC6 instead of single TVS 5V diode
  - choose USBLC6
